# Generated by Django 3.2.23 on 2023-12-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_auto_20231209_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='monday',
            field=models.BooleanField(default=False),
        ),
    ]
