# Generated by Django 3.2.23 on 2023-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_auto_20231216_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.CharField(default='fsfd', max_length=50),
            preserve_default=False,
        ),
    ]
